name = "willowacademy"
author = "jitter, vibriwhisker, silphn"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3c962109ca4e2dd91e989fb4f1db6aa577cc34a31cd368ff173b8b29a009d583"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
